In [3]:
import torch 
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

#For reproducibility
torch.manual_seed(1)

In [5]:
#Data
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[1],[2],[3]])
print(x_train)
print(x_train.shape)
print(y_train)
print(y_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])
tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [6]:
# Weight Initialization
W = torch.zeros(1, requires_grad = True)
print(W)
b = torch.zeros(1, requires_grad = True)
print(b)

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


In [7]:
#Hypothesis
hypothesis = x_train*W+b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [9]:
#Cost
print(hypothesis)
print(y_train)
print(hypothesis - y_train)
print((hypothesis - y_train) ** 2)
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)
tensor([[1.],
        [2.],
        [3.]])
tensor([[-1.],
        [-2.],
        [-3.]], grad_fn=<SubBackward0>)
tensor([[1.],
        [4.],
        [9.]], grad_fn=<PowBackward0>)
tensor(4.6667, grad_fn=<MeanBackward0>)


In [11]:
#Gradient Descent(경사 하강법)
optimizer = optim.SGD([W, b],lr=0.01)
#SGD = 확률적 경사 하강법(Stochastic Gradient Descent)
optimizer.zero_grad()
cost.backward()
optimizer.step()
print(W)
print(b)

tensor([0.0933], requires_grad=True)
tensor([0.0400], requires_grad=True)


In [13]:
#hypothesis가 좋아졌는지 확인
hypothesis = x_train * W + b
print(hypothesis)
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor([[0.1333],
        [0.2267],
        [0.3200]], grad_fn=<AddBackward0>)
tensor(3.6927, grad_fn=<MeanBackward0>)


# Training with full code

In [15]:
#데이터
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[1],[2],[3]])
#모델 초기화 
W = torch.zeros(1, requires_grad = True)
b = torch.zeros(1, requires_grad = True)
#optimizer 설정
optimizer = optim.SGD([W,b], lr=0.01)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):
    
    #H(x) 계산 
    hypothesis = x_train *W + b
    
    #cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)
    
    #cost로 H(x)개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    #100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/1000 W: 0.093, b: 0.040 Cost: 4.666667
Epoch  100/1000 W: 0.873, b: 0.289 Cost: 0.012043
Epoch  200/1000 W: 0.900, b: 0.227 Cost: 0.007442
Epoch  300/1000 W: 0.921, b: 0.179 Cost: 0.004598
Epoch  400/1000 W: 0.938, b: 0.140 Cost: 0.002842
Epoch  500/1000 W: 0.951, b: 0.110 Cost: 0.001756
Epoch  600/1000 W: 0.962, b: 0.087 Cost: 0.001085
Epoch  700/1000 W: 0.970, b: 0.068 Cost: 0.000670
Epoch  800/1000 W: 0.976, b: 0.054 Cost: 0.000414
Epoch  900/1000 W: 0.981, b: 0.042 Cost: 0.000256
Epoch 1000/1000 W: 0.985, b: 0.033 Cost: 0.000158


# High-level Implementation with nn.Module

In [20]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)

    def forward(self, x):
        return self.linear(x)

model = LinearRegressionModel()



In [21]:
#Hypothesis
hypothesis = model(x_train)
print(hypothesis)

tensor([[-0.3417],
        [-1.2832],
        [-2.2246]], grad_fn=<AddmmBackward0>)


In [22]:
#Cost (mean squared error (MSE)로 구함)
print(hypothesis)
print(y_train)

cost = F.mse_loss(hypothesis, y_train)
print(cost)


tensor([[-0.3417],
        [-1.2832],
        [-2.2246]], grad_fn=<AddmmBackward0>)
tensor([[1.],
        [2.],
        [3.]])
tensor(13.2919, grad_fn=<MseLossBackward0>)


In [23]:
#Gradient Descent 
optimizer = optim.SGD(model.parameters(), lr=0.01)
optimizer.zero_grad()
cost.backward()
optimizer.step()

# Training with full code

In [24]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])
# 모델 초기화
model = LinearRegressionModel()
# optimizer 설정
optimizer = optim.SGD(model.parameters(), lr=0.01)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):
    
    # H(x) 계산
    prediction = model(x_train)
    
    # cost 계산
    cost = F.mse_loss(prediction, y_train)
    
    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # 100번마다 로그 출력
    if epoch % 100 == 0:
        params = list(model.parameters())
        W = params[0].item()
        b = params[1].item()
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W, b, cost.item()
        ))

Epoch    0/1000 W: -0.114, b: 0.547 Cost: 4.589475
Epoch  100/1000 W: 0.700, b: 0.683 Cost: 0.067199
Epoch  200/1000 W: 0.764, b: 0.537 Cost: 0.041525
Epoch  300/1000 W: 0.814, b: 0.422 Cost: 0.025660
Epoch  400/1000 W: 0.854, b: 0.332 Cost: 0.015856
Epoch  500/1000 W: 0.885, b: 0.261 Cost: 0.009798
Epoch  600/1000 W: 0.910, b: 0.205 Cost: 0.006055
Epoch  700/1000 W: 0.929, b: 0.161 Cost: 0.003741
Epoch  800/1000 W: 0.944, b: 0.127 Cost: 0.002312
Epoch  900/1000 W: 0.956, b: 0.100 Cost: 0.001429
Epoch 1000/1000 W: 0.966, b: 0.078 Cost: 0.000883
